// Generated by gencpp from file piksi_rtk_msgs/EnuOriginRequest.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_ENUORIGINREQUEST_H
#define PIKSI_RTK_MSGS_MESSAGE_ENUORIGINREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace piksi_rtk_msgs
{
template <class ContainerAllocator>
struct EnuOriginRequest_
{
  typedef EnuOriginRequest_<ContainerAllocator> Type;

  EnuOriginRequest_()
    : lat(0.0)
    , lon(0.0)
    , alt(0.0)  {
    }
  EnuOriginRequest_(const ContainerAllocator& _alloc)
    : lat(0.0)
    , lon(0.0)
    , alt(0.0)  {
  (void)_alloc;
    }



   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;

   typedef double _alt_type;
  _alt_type alt;





  typedef boost::shared_ptr< ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EnuOriginRequest_

typedef ::piksi_rtk_msgs::EnuOriginRequest_<std::allocator<void> > EnuOriginRequest;

typedef boost::shared_ptr< ::piksi_rtk_msgs::EnuOriginRequest > EnuOriginRequestPtr;
typedef boost::shared_ptr< ::piksi_rtk_msgs::EnuOriginRequest const> EnuOriginRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator1> & lhs, const ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator2> & rhs)
{
  return lhs.lat == rhs.lat &&
    lhs.lon == rhs.lon &&
    lhs.alt == rhs.alt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator1> & lhs, const ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace piksi_rtk_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "800b265188e13fdc7e121024d9b6fa27";
  }

  static const char* value(const ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x800b265188e13fdcULL;
  static const uint64_t static_value2 = 0x7e121024d9b6fa27ULL;
};

template<class ContainerAllocator>
struct DataType< ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piksi_rtk_msgs/EnuOriginRequest";
  }

  static const char* value(const ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 lat\n"
"float64 lon\n"
"float64 alt\n"
;
  }

  static const char* value(const ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.alt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnuOriginRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piksi_rtk_msgs::EnuOriginRequest_<ContainerAllocator>& v)
  {
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "alt: ";
    Printer<double>::stream(s, indent + "  ", v.alt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_ENUORIGINREQUEST_H
