// Generated by gencpp from file piksi_rtk_msgs/EnuOrigin.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_ENUORIGIN_H
#define PIKSI_RTK_MSGS_MESSAGE_ENUORIGIN_H

#include <ros/service_traits.h>


#include <piksi_rtk_msgs/EnuOriginRequest.h>
#include <piksi_rtk_msgs/EnuOriginResponse.h>


namespace piksi_rtk_msgs
{

struct EnuOrigin
{

typedef EnuOriginRequest Request;
typedef EnuOriginResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnuOrigin
} // namespace piksi_rtk_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::piksi_rtk_msgs::EnuOrigin > {
  static const char* value()
  {
    return "800b265188e13fdc7e121024d9b6fa27";
  }

  static const char* value(const ::piksi_rtk_msgs::EnuOrigin&) { return value(); }
};

template<>
struct DataType< ::piksi_rtk_msgs::EnuOrigin > {
  static const char* value()
  {
    return "piksi_rtk_msgs/EnuOrigin";
  }

  static const char* value(const ::piksi_rtk_msgs::EnuOrigin&) { return value(); }
};


// service_traits::MD5Sum< ::piksi_rtk_msgs::EnuOriginRequest> should match
// service_traits::MD5Sum< ::piksi_rtk_msgs::EnuOrigin >
template<>
struct MD5Sum< ::piksi_rtk_msgs::EnuOriginRequest>
{
  static const char* value()
  {
    return MD5Sum< ::piksi_rtk_msgs::EnuOrigin >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::EnuOriginRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::piksi_rtk_msgs::EnuOriginRequest> should match
// service_traits::DataType< ::piksi_rtk_msgs::EnuOrigin >
template<>
struct DataType< ::piksi_rtk_msgs::EnuOriginRequest>
{
  static const char* value()
  {
    return DataType< ::piksi_rtk_msgs::EnuOrigin >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::EnuOriginRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::piksi_rtk_msgs::EnuOriginResponse> should match
// service_traits::MD5Sum< ::piksi_rtk_msgs::EnuOrigin >
template<>
struct MD5Sum< ::piksi_rtk_msgs::EnuOriginResponse>
{
  static const char* value()
  {
    return MD5Sum< ::piksi_rtk_msgs::EnuOrigin >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::EnuOriginResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::piksi_rtk_msgs::EnuOriginResponse> should match
// service_traits::DataType< ::piksi_rtk_msgs::EnuOrigin >
template<>
struct DataType< ::piksi_rtk_msgs::EnuOriginResponse>
{
  static const char* value()
  {
    return DataType< ::piksi_rtk_msgs::EnuOrigin >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::EnuOriginResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_ENUORIGIN_H
