// Generated by gencpp from file piksi_rtk_msgs/InfoWifiCorrections.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_INFOWIFICORRECTIONS_H
#define PIKSI_RTK_MSGS_MESSAGE_INFOWIFICORRECTIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace piksi_rtk_msgs
{
template <class ContainerAllocator>
struct InfoWifiCorrections_
{
  typedef InfoWifiCorrections_<ContainerAllocator> Type;

  InfoWifiCorrections_()
    : header()
    , received_corrections(0)
    , latency(0.0)  {
    }
  InfoWifiCorrections_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , received_corrections(0)
    , latency(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _received_corrections_type;
  _received_corrections_type received_corrections;

   typedef float _latency_type;
  _latency_type latency;





  typedef boost::shared_ptr< ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> const> ConstPtr;

}; // struct InfoWifiCorrections_

typedef ::piksi_rtk_msgs::InfoWifiCorrections_<std::allocator<void> > InfoWifiCorrections;

typedef boost::shared_ptr< ::piksi_rtk_msgs::InfoWifiCorrections > InfoWifiCorrectionsPtr;
typedef boost::shared_ptr< ::piksi_rtk_msgs::InfoWifiCorrections const> InfoWifiCorrectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator1> & lhs, const ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.received_corrections == rhs.received_corrections &&
    lhs.latency == rhs.latency;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator1> & lhs, const ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace piksi_rtk_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "925248c7afa695eb59c83cfd29d8c57c";
  }

  static const char* value(const ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x925248c7afa695ebULL;
  static const uint64_t static_value2 = 0x59c83cfd29d8c57cULL;
};

template<class ContainerAllocator>
struct DataType< ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piksi_rtk_msgs/InfoWifiCorrections";
  }

  static const char* value(const ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Information about Corrections received over WiFi.\n"
"\n"
"Header header\n"
"\n"
"uint32 received_corrections # number of correction received from start up\n"
"float32 latency # latency from base station, -1 if not sampled [ms].\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.received_corrections);
      stream.next(m.latency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InfoWifiCorrections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piksi_rtk_msgs::InfoWifiCorrections_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "received_corrections: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.received_corrections);
    s << indent << "latency: ";
    Printer<float>::stream(s, indent + "  ", v.latency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_INFOWIFICORRECTIONS_H
