// Generated by gencpp from file piksi_rtk_msgs/PositionWithCovarianceStamped.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_POSITIONWITHCOVARIANCESTAMPED_H
#define PIKSI_RTK_MSGS_MESSAGE_POSITIONWITHCOVARIANCESTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <piksi_rtk_msgs/PositionWithCovariance.h>

namespace piksi_rtk_msgs
{
template <class ContainerAllocator>
struct PositionWithCovarianceStamped_
{
  typedef PositionWithCovarianceStamped_<ContainerAllocator> Type;

  PositionWithCovarianceStamped_()
    : header()
    , position()  {
    }
  PositionWithCovarianceStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::piksi_rtk_msgs::PositionWithCovariance_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> const> ConstPtr;

}; // struct PositionWithCovarianceStamped_

typedef ::piksi_rtk_msgs::PositionWithCovarianceStamped_<std::allocator<void> > PositionWithCovarianceStamped;

typedef boost::shared_ptr< ::piksi_rtk_msgs::PositionWithCovarianceStamped > PositionWithCovarianceStampedPtr;
typedef boost::shared_ptr< ::piksi_rtk_msgs::PositionWithCovarianceStamped const> PositionWithCovarianceStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator1> & lhs, const ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator1> & lhs, const ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace piksi_rtk_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a563e78c9db9c3702ffc2635534bd52";
  }

  static const char* value(const ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a563e78c9db9c37ULL;
  static const uint64_t static_value2 = 0x02ffc2635534bd52ULL;
};

template<class ContainerAllocator>
struct DataType< ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piksi_rtk_msgs/PositionWithCovarianceStamped";
  }

  static const char* value(const ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"piksi_rtk_msgs/PositionWithCovariance position\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: piksi_rtk_msgs/PositionWithCovariance\n"
"geometry_msgs/Point position\n"
"float64[9] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PositionWithCovarianceStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piksi_rtk_msgs::PositionWithCovarianceStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::piksi_rtk_msgs::PositionWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_POSITIONWITHCOVARIANCESTAMPED_H
