// Generated by gencpp from file piksi_rtk_msgs/SamplePositionResponse.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_SAMPLEPOSITIONRESPONSE_H
#define PIKSI_RTK_MSGS_MESSAGE_SAMPLEPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace piksi_rtk_msgs
{
template <class ContainerAllocator>
struct SamplePositionResponse_
{
  typedef SamplePositionResponse_<ContainerAllocator> Type;

  SamplePositionResponse_()
    {
    }
  SamplePositionResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SamplePositionResponse_

typedef ::piksi_rtk_msgs::SamplePositionResponse_<std::allocator<void> > SamplePositionResponse;

typedef boost::shared_ptr< ::piksi_rtk_msgs::SamplePositionResponse > SamplePositionResponsePtr;
typedef boost::shared_ptr< ::piksi_rtk_msgs::SamplePositionResponse const> SamplePositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace piksi_rtk_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piksi_rtk_msgs/SamplePositionResponse";
  }

  static const char* value(const ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SamplePositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::piksi_rtk_msgs::SamplePositionResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_SAMPLEPOSITIONRESPONSE_H
