// Generated by gencpp from file piksi_rtk_msgs/SamplePosition.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_SAMPLEPOSITION_H
#define PIKSI_RTK_MSGS_MESSAGE_SAMPLEPOSITION_H

#include <ros/service_traits.h>


#include <piksi_rtk_msgs/SamplePositionRequest.h>
#include <piksi_rtk_msgs/SamplePositionResponse.h>


namespace piksi_rtk_msgs
{

struct SamplePosition
{

typedef SamplePositionRequest Request;
typedef SamplePositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SamplePosition
} // namespace piksi_rtk_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::piksi_rtk_msgs::SamplePosition > {
  static const char* value()
  {
    return "d61ca547d7fe6fd48751a949f576f865";
  }

  static const char* value(const ::piksi_rtk_msgs::SamplePosition&) { return value(); }
};

template<>
struct DataType< ::piksi_rtk_msgs::SamplePosition > {
  static const char* value()
  {
    return "piksi_rtk_msgs/SamplePosition";
  }

  static const char* value(const ::piksi_rtk_msgs::SamplePosition&) { return value(); }
};


// service_traits::MD5Sum< ::piksi_rtk_msgs::SamplePositionRequest> should match
// service_traits::MD5Sum< ::piksi_rtk_msgs::SamplePosition >
template<>
struct MD5Sum< ::piksi_rtk_msgs::SamplePositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::piksi_rtk_msgs::SamplePosition >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SamplePositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::piksi_rtk_msgs::SamplePositionRequest> should match
// service_traits::DataType< ::piksi_rtk_msgs::SamplePosition >
template<>
struct DataType< ::piksi_rtk_msgs::SamplePositionRequest>
{
  static const char* value()
  {
    return DataType< ::piksi_rtk_msgs::SamplePosition >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SamplePositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::piksi_rtk_msgs::SamplePositionResponse> should match
// service_traits::MD5Sum< ::piksi_rtk_msgs::SamplePosition >
template<>
struct MD5Sum< ::piksi_rtk_msgs::SamplePositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::piksi_rtk_msgs::SamplePosition >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SamplePositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::piksi_rtk_msgs::SamplePositionResponse> should match
// service_traits::DataType< ::piksi_rtk_msgs::SamplePosition >
template<>
struct DataType< ::piksi_rtk_msgs::SamplePositionResponse>
{
  static const char* value()
  {
    return DataType< ::piksi_rtk_msgs::SamplePosition >::value();
  }
  static const char* value(const ::piksi_rtk_msgs::SamplePositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_SAMPLEPOSITION_H
