// Generated by gencpp from file piksi_rtk_msgs/UtcTimeMulti.msg
// DO NOT EDIT!


#ifndef PIKSI_RTK_MSGS_MESSAGE_UTCTIMEMULTI_H
#define PIKSI_RTK_MSGS_MESSAGE_UTCTIMEMULTI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace piksi_rtk_msgs
{
template <class ContainerAllocator>
struct UtcTimeMulti_
{
  typedef UtcTimeMulti_<ContainerAllocator> Type;

  UtcTimeMulti_()
    : header()
    , flags(0)
    , tow(0)
    , year(0)
    , month(0)
    , day(0)
    , hours(0)
    , minutes(0)
    , seconds(0)
    , ns(0)  {
    }
  UtcTimeMulti_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , flags(0)
    , tow(0)
    , year(0)
    , month(0)
    , day(0)
    , hours(0)
    , minutes(0)
    , seconds(0)
    , ns(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _flags_type;
  _flags_type flags;

   typedef uint32_t _tow_type;
  _tow_type tow;

   typedef uint16_t _year_type;
  _year_type year;

   typedef uint8_t _month_type;
  _month_type month;

   typedef uint8_t _day_type;
  _day_type day;

   typedef uint8_t _hours_type;
  _hours_type hours;

   typedef uint8_t _minutes_type;
  _minutes_type minutes;

   typedef uint8_t _seconds_type;
  _seconds_type seconds;

   typedef uint32_t _ns_type;
  _ns_type ns;





  typedef boost::shared_ptr< ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> const> ConstPtr;

}; // struct UtcTimeMulti_

typedef ::piksi_rtk_msgs::UtcTimeMulti_<std::allocator<void> > UtcTimeMulti;

typedef boost::shared_ptr< ::piksi_rtk_msgs::UtcTimeMulti > UtcTimeMultiPtr;
typedef boost::shared_ptr< ::piksi_rtk_msgs::UtcTimeMulti const> UtcTimeMultiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator1> & lhs, const ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.flags == rhs.flags &&
    lhs.tow == rhs.tow &&
    lhs.year == rhs.year &&
    lhs.month == rhs.month &&
    lhs.day == rhs.day &&
    lhs.hours == rhs.hours &&
    lhs.minutes == rhs.minutes &&
    lhs.seconds == rhs.seconds &&
    lhs.ns == rhs.ns;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator1> & lhs, const ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace piksi_rtk_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> >
{
  static const char* value()
  {
    return "305f41bf5fdb87de324a10b06c47c614";
  }

  static const char* value(const ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x305f41bf5fdb87deULL;
  static const uint64_t static_value2 = 0x324a10b06c47c614ULL;
};

template<class ContainerAllocator>
struct DataType< ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> >
{
  static const char* value()
  {
    return "piksi_rtk_msgs/UtcTimeMulti";
  }

  static const char* value(const ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message reports the Universal Coordinated Time (UTC). Note the flags which\n"
"# indicate the source of the UTC offset value and source of the time fix.\n"
"\n"
"Header header\n"
"\n"
"uint8 flags   # Indicates source and time validity\n"
"uint32 tow    # GPS time of week rounded to the nearest millisecond\n"
"uint16 year   # Year\n"
"uint8 month   # Month (range 1 .. 12)\n"
"uint8 day     # days in the month (range 1-31)\n"
"uint8 hours   # hours of day (range 0-23)\n"
"uint8 minutes # minutes of hour (range 0-59)\n"
"uint8 seconds # seconds of minute (range 0-60) rounded down\n"
"uint32 ns     # nanoseconds of second (range 0-999999999)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.flags);
      stream.next(m.tow);
      stream.next(m.year);
      stream.next(m.month);
      stream.next(m.day);
      stream.next(m.hours);
      stream.next(m.minutes);
      stream.next(m.seconds);
      stream.next(m.ns);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UtcTimeMulti_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::piksi_rtk_msgs::UtcTimeMulti_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "flags: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flags);
    s << indent << "tow: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tow);
    s << indent << "year: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.year);
    s << indent << "month: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.month);
    s << indent << "day: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.day);
    s << indent << "hours: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hours);
    s << indent << "minutes: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.minutes);
    s << indent << "seconds: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.seconds);
    s << indent << "ns: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ns);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIKSI_RTK_MSGS_MESSAGE_UTCTIMEMULTI_H
